export const RS_MENUR_ROOMS = [
  "ALAMANDA", "ANGGREK", "FARMASI + CSSD", "FLAMBOYAN", "GELATIK", "ICU",
  "IGD", "JATAYU / KENARI", "KESWARA", "LABORATORIUM", "LILI", "LT IV - SAKURA",
  "NAPZA", "NICU", "OK", "POLI ANAK", "POLI GIGI", "POLI LT 1",
  "POLI LT 2", "POLI REHAB MEDIK", "POLI SYARAF", "POLI UMUM LT 3", "RADIOLOGI", "TULIP"
];
